// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyWziG0cM0UoRU0QRKySV8RjuYo7iuqVE',
    appId: '1:551368829561:web:fc59fafcd6f7672a3242a8',
    messagingSenderId: '551368829561',
    projectId: 'module6-81226',
    authDomain: 'module6-81226.firebaseapp.com',
    storageBucket: 'module6-81226.firebasestorage.app',
    measurementId: 'G-FE1FGLZC64',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8f-ZB9f9NIo2tuq8GjzYB0dmZIxMK31Q',
    appId: '1:551368829561:ios:1dd68ce81250cede3242a8',
    messagingSenderId: '551368829561',
    projectId: 'module6-81226',
    storageBucket: 'module6-81226.firebasestorage.app',
    iosBundleId: 'com.example.module6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8f-ZB9f9NIo2tuq8GjzYB0dmZIxMK31Q',
    appId: '1:551368829561:ios:1dd68ce81250cede3242a8',
    messagingSenderId: '551368829561',
    projectId: 'module6-81226',
    storageBucket: 'module6-81226.firebasestorage.app',
    iosBundleId: 'com.example.module6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyWziG0cM0UoRU0QRKySV8RjuYo7iuqVE',
    appId: '1:551368829561:web:8e9b3c24ff5aa0353242a8',
    messagingSenderId: '551368829561',
    projectId: 'module6-81226',
    authDomain: 'module6-81226.firebaseapp.com',
    storageBucket: 'module6-81226.firebasestorage.app',
    measurementId: 'G-W0S97EYPRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDveOmH0Rd12oc007Kvr67qtEp4zeHlAUY',
    appId: '1:551368829561:android:9f6f9e69e009f96a3242a8',
    messagingSenderId: '551368829561',
    projectId: 'module6-81226',
    storageBucket: 'module6-81226.firebasestorage.app',
  );

}